Repository archethic-foundation/archethic-node, pull requests merged in 2021-09, with the labels that each got.

#59 Added Alpinejs
  assets/js/app.js
  assets/package-lock.json
  assets/package.json
Labels: good first issue, UI

#74 Fix the testnet genesis overloading on runtime
  lib/archethic/bootstrap.ex
  lib/archethic/bootstrap/network_init.ex
  lib/archethic/utils/benchmarks/balance.ex
  mix.exs
Labels: bug

#76 Added Beacon Explorer
  lib/archethic/beacon_chain/summary_timer.ex
  lib/archethic/pub_sub.ex
  lib/archethic/self_repair/sync/beacon_summary_handler.ex
  lib/archethic_web/live/chains/beacon_live.ex
  lib/archethic_web/router.ex
  lib/archethic_web/templates/explorer/beacon_chain_index.html.leex
  lib/archethic_web/templates/layout/root.html.eex
  lib/archethic_web/views/layout_helpers.ex
  mix.exs
Labels: enhancement, UI, BeaconChain
