Repository archethic-foundation/archethic-node, pull requests merged in 2022-08, with the labels that each got.

#483 Include UCO transfer towards burning address
  lib/archethic/account/mem_tables_loader.ex
  lib/archethic/bootstrap/network_init.ex
  lib/archethic/mining/distributed_workflow.ex
  lib/archethic/mining/standalone_workflow.ex
  lib/archethic/mining/validation_context.ex
  lib/archethic/replication/transaction_validator.ex
  lib/archethic/transaction_chain.ex
  lib/archethic/transaction_chain/transaction/validation_stamp/ledger_operations.ex
  lib/archethic_web/templates/explorer/transaction_details.html.leex
  lib/archethic_web/views/explorer_view.ex
  test/archethic/bootstrap/network_init_test.exs
  test/archethic/mining/validation_context_test.exs
  test/archethic/replication_test.exs
  test/support/transaction_factory.ex
Labels: bug, Fee

#487 Correct self repair notifier
  lib/archethic/self_repair/notifier.ex
  test/archethic/self_repair/notifier_test.exs
Labels: bug, self repair

#475 Notify validation error to the welcome node
  lib/archethic/mining/distributed_workflow.ex
  lib/archethic/mining/standalone_workflow.ex
  lib/archethic/p2p/message.ex
  lib/archethic/p2p/message/validation_error.ex
  lib/archethic_web/graphql_schema.ex
  lib/archethic_web/graphql_schema/transaction_error.ex
  lib/archethic_web/transaction_subscriber.ex
Labels: feature

#489 Return fully validated transaction on Transaction Subscriber#456 #489
  lib/archethic_web/graphql_schema/transaction_attestation.ex
  lib/archethic_web/transaction_subscriber.ex
Labels: feature, API

#485 Testing for Reward Minting #484
  lib/archethic/account/mem_tables_loader.ex
  test/archethic/account/mem_tables_loader_test.exs
  test/archethic/account_test.exs
  test/archethic/bootstrap/network_init_test.exs
  test/archethic/bootstrap/sync_test.exs
  test/archethic/bootstrap_test.exs
  test/archethic/reward/mem_tables_loader_test.exs
  test/archethic/reward_test.exs
  test/support/template.ex
Labels: testing

#496 Documentation Update in GraphQL #492
  lib/archethic_web/graphql_schema/transaction_type.ex
Labels: documentation

#501 Addition of Inherit Constraints to Network Transactions #422
  lib/archethic/bootstrap/transaction_handler.ex
  lib/archethic/reward.ex
Labels: feature

#511 Fix interpreter from examples
  lib/archethic/contracts/contract/constants.ex
  lib/archethic/contracts/interpreter.ex
  lib/archethic/contracts/interpreter/transaction_statements.ex
  lib/archethic/db/embedded_impl/encoding.ex
  lib/archethic/mining/standalone_workflow.ex
  lib/archethic/utils/regression/playbooks/smart_contract.ex
  test/archethic/contracts/interpreter_test.exs
  test/archethic/contracts/worker_test.exs
  test/archethic/contracts_test.exs
Labels: bug

#513 Return more details error from the replication
  lib/archethic/mining/distributed_workflow.ex
  lib/archethic/mining/pending_transaction_validation.ex
  lib/archethic/mining/standalone_workflow.ex
  lib/archethic/mining/validation_context.ex
  lib/archethic/p2p/message.ex
  lib/archethic/p2p/message/replication_error.ex
  lib/archethic/p2p/message/validation_error.ex
  lib/archethic/replication.ex
  lib/archethic/replication/transaction_validator.ex
  lib/archethic/transaction_chain/transaction.ex
  lib/archethic/transaction_chain/transaction/cross_validation_stamp.ex
  lib/archethic/transaction_chain/transaction/validation_stamp.ex
  lib/archethic_web/graphql_schema/transaction_error.ex
  lib/archethic_web/transaction_subscriber.ex
  test/archethic/mining/validation_context_test.exs
Labels: feature

#529 Fix max confirmations
  lib/archethic_web/transaction_subscriber.ex
Labels: bug, API

#527 Resolve last address conflicts
  lib/archethic/db.ex
  lib/archethic/db/embedded_impl.ex
  lib/archethic/db/embedded_impl/chain_index.ex
  lib/archethic/mining/pending_transaction_validation.ex
  lib/archethic/oracle_chain/scheduler.ex
  lib/archethic/p2p/message.ex
  lib/archethic/p2p/message/last_transaction_address.ex
  lib/archethic/transaction_chain.ex
  lib/archethic_web/live/chains/oracle_live.ex
  test/archethic/bootstrap/network_init_test.exs
  test/archethic/bootstrap/sync_test.exs
  test/archethic/bootstrap_test.exs
  test/archethic/db/embedded_impl/chain_index_test.exs
  test/archethic/db/embedded_impl_test.exs
  test/archethic/mining/pending_transaction_validation_test.exs
  test/archethic/p2p/messages_test.exs
  test/archethic/replication_test.exs
  test/archethic/transaction_chain_test.exs
  test/archethic_test.exs
  test/support/template.ex
Labels: feature, P2P

#528 Fix get transaction chain lookup
  lib/archethic.ex
  lib/archethic/db.ex
  lib/archethic/db/embedded_impl.ex
  lib/archethic/db/embedded_impl/chain_reader.ex
  lib/archethic/transaction_chain.ex
  test/archethic/db/embedded_impl_test.exs
  test/archethic_test.exs
  test/support/template.ex
Labels: bug, P2P

#531 Fix dialyzer plts folder creation
  mix.exs
Labels: bug, quality

#530 Election with only available and authorized nodes
  lib/archethic.ex
  lib/archethic/bootstrap/transaction_handler.ex
  lib/archethic/contracts/interpreter/library.ex
  lib/archethic/mining/pending_transaction_validation.ex
  lib/archethic/replication/transaction_context.ex
  lib/archethic/self_repair/sync/transaction_handler.ex
  lib/archethic/transaction_chain.ex
  test/archethic/account_test.exs
  test/archethic/beacon_chain_test.exs
  test/archethic/bootstrap/transaction_handler_test.exs
  test/archethic/mining/distributed_workflow_test.exs
  test/archethic/self_repair/sync/transaction_handler_test.exs
  test/archethic/self_repair/sync_test.exs
Labels: bug, core team

#533 Get token id in the API
  lib/archethic_web/graphql_schema/resolver.ex
  lib/archethic_web/graphql_schema/transaction_type.ex
Labels: feature, API

#537 Fix bootstrap issue
  lib/archethic/beacon_chain.ex
  lib/archethic/bootstrap.ex
  lib/archethic/p2p/client.ex
  lib/archethic/p2p/client/connection.ex
  lib/archethic/p2p/client/default_impl.ex
  lib/archethic/p2p/listener.ex
  lib/archethic/p2p/listener_protocol.ex
Labels: bug, bootstrap

#532 Add API to get last oracle value
  lib/archethic/oracle_chain.ex
  lib/archethic/oracle_chain/mem_table.ex
  lib/archethic/oracle_chain/mem_table_loader.ex
  lib/archethic_web/graphql_schema.ex
  lib/archethic_web/graphql_schema/datetime_type.ex
  lib/archethic_web/graphql_schema/oracle_data.ex
  test/archethic/oracle_chain/mem_table_loader_test.exs
Labels: feature, API

#538 Prevent scheduling network tx
  lib/archethic/bootstrap/network_init.ex
  lib/archethic/oracle_chain.ex
  lib/archethic/oracle_chain/scheduler.ex
  lib/archethic/oracle_chain/supervisor.ex
  lib/archethic/pub_sub.ex
  lib/archethic/reward.ex
  lib/archethic/reward/scheduler.ex
  lib/archethic/shared_secrets.ex
  lib/archethic/shared_secrets/node_renewal.ex
  lib/archethic/shared_secrets/node_renewal_scheduler.ex
  lib/archethic/transaction_chain/transaction.ex
  lib/archethic/utils/regression/playbook.ex
  test/archethic/oracle_chain/scheduler_test.exs
  test/archethic/reward/scheduler_test.exs
  test/archethic/shared_secrets/node_renewal_scheduler_test.exs
  test/archethic/shared_secrets/node_renewal_test.exs
Labels: bug, P2P, oracle chain, shared secrets, rewards

#534 Verify scheduled transaction only happens once
  config/test.exs
  lib/archethic/mining/pending_transaction_validation.ex
  lib/archethic/oracle_chain.ex
  lib/archethic/reward.ex
  lib/archethic/shared_secrets.ex
  test/archethic/mining/pending_transaction_validation_test.exs
Labels: bug, mining, oracle chain, shared secrets

#539 Clean Node movements references
  lib/archethic/transaction_chain/transaction/cross_validation_stamp.ex
  lib/archethic/transaction_chain/transaction/validation_stamp/ledger_operations.ex
  lib/archethic_web/controllers/api/transaction_controller.ex
  lib/archethic_web/graphql_schema/transaction_type.ex
  test/archethic/transaction_chain/transaction/cross_validation_stamp_test.exs
  test/archethic_web/controllers/api/transaction_controller_test.exs
Labels: documentation

#547 Add DB writers pool
  lib/archethic/db/embedded_impl.ex
  lib/archethic/db/embedded_impl/chain_writer.ex
  lib/archethic/db/embedded_impl/queue.ex
  lib/archethic/db/embedded_impl/supervisor.ex
  test/archethic/db/embedded_impl/chain_index_test.exs
Labels: DB

#506 Improved beacon explorer loadtime
  lib/archethic_web/live/chains/beacon_live.ex
Labels: feature

#546 Fix node shared secrets schedulers
  lib/archethic/mining/pending_transaction_validation.ex
  lib/archethic/shared_secrets/node_renewal.ex
  lib/archethic/shared_secrets/node_renewal_scheduler.ex
  test/archethic/mining/pending_transaction_validation_test.exs
  test/archethic/shared_secrets/node_renewal_test.exs
Labels: bug, mining, shared secrets, rewards

#545 Fix replication transaction chain ordering writing
  lib/archethic/replication.ex
  lib/archethic/telemetry.ex
  test/archethic/bootstrap/network_init_test.exs
  test/archethic/replication_test.exs
  test/archethic/self_repair/sync/transaction_handler_test.exs
  test/archethic/self_repair/sync_test.exs
Labels: bug, replication

#550 Add timeout in standalone workflow
  config/config.exs
  lib/archethic/mining/standalone_workflow.ex
Labels: bug, mining
