Repository archethic-foundation/archethic-node, pull requests merged in 2022-09, with the labels that each got.

#553 Archethic Node cron scheduler wrongly configured #540
  lib/archethic/contracts/contract.ex
  lib/archethic/contracts/interpreter.ex
  lib/archethic/contracts/worker.ex
  lib/archethic/utils.ex
  test/archethic/contracts/worker_test.exs
Labels: bug, smart contracts

#555 Fix unspent outputs amount
  lib/archethic/transaction_chain/transaction/validation_stamp/ledger_operations.ex
Labels: bug, mining

#549 TokenAddress naming #525
  lib/archethic/account/mem_tables_loader.ex
  lib/archethic/contracts/contract/constants.ex
  lib/archethic/contracts/interpreter/transaction_statements.ex
  lib/archethic/reward.ex
  lib/archethic/transaction_chain/transaction.ex
  lib/archethic/transaction_chain/transaction/data/ledger.ex
  lib/archethic/transaction_chain/transaction/data/ledger/token.ex
  lib/archethic/transaction_chain/transaction/data/ledger/token/transfer.ex
  lib/archethic/utils/regression/playbook.ex
  lib/archethic_web/controllers/api/schema/token_ledger.ex
  lib/archethic_web/templates/explorer/transaction_details.html.leex
  test/archethic/contracts/worker_test.exs
  test/archethic/reward_test.exs
  test/archethic/transaction_chain/transaction_data/token_test.exs
  test/archethic_web/controllers/api/transaction_payload_test.exs
Labels: bug, breaking change

#559 Drop transaction in beacon chains for slot and summaries
  config/test.exs
  lib/archethic/beacon_chain.ex
  lib/archethic/beacon_chain/subset.ex
  lib/archethic/beacon_chain/subset/summary_cache.ex
  lib/archethic/beacon_chain/subset/supervisor.ex
  lib/archethic/beacon_chain/summary.ex
  lib/archethic/beacon_chain/update.ex
  lib/archethic/bootstrap/network_init.ex
  lib/archethic/db.ex
  lib/archethic/db/embedded_impl.ex
  lib/archethic/db/embedded_impl/chain_index.ex
  lib/archethic/db/embedded_impl/chain_reader.ex
  lib/archethic/db/embedded_impl/chain_writer.ex
  lib/archethic/db/embedded_impl/supervisor.ex
  lib/archethic/mining/distributed_workflow.ex
  lib/archethic/mining/standalone_workflow.ex
  lib/archethic/p2p/message.ex
  lib/archethic/p2p/message/get_current_summaries.ex
  lib/archethic/p2p/message/new_beacon_slot.ex
  lib/archethic/p2p/message/new_beacon_transaction.ex
  lib/archethic/p2p/message/transaction_summary_list.ex
  lib/archethic/replication.ex
  lib/archethic/transaction_chain.ex
  lib/archethic/transaction_chain/mem_tables_loader.ex
  lib/archethic/transaction_chain/transaction.ex
  lib/archethic/utils.ex
  lib/archethic_web/live/chains/beacon_live.ex
  lib/archethic_web/live/chains/cache.ex
  lib/archethic_web/live/top_transactions_live.ex
  test/archethic/beacon_chain/subset/summary_cache_test.exs
  test/archethic/beacon_chain/subset_test.exs
  test/archethic/beacon_chain/update_test.exs
  test/archethic/beacon_chain_test.exs
  test/archethic/db/embedded_impl_test.exs
Labels: breaking change

#562 Remove used messages tracking in the PortHandler
  lib/archethic/utils/port_handler.ex
Labels: bug, system

#571 Fix faucet limitation
  lib/archethic_web/controllers/faucet_controller.ex
  lib/archethic_web/transaction_subscriber.ex
  test/archethic_web/controllers/faucet_controller_test.exs
Labels: bug, UI

#572 Add nearest_endpoints GraphQL query
  lib/archethic_web/graphl_context.ex
  lib/archethic_web/graphql_schema.ex
  lib/archethic_web/graphql_schema/p2p_type.ex
  lib/archethic_web/graphql_schema/resolver.ex
  lib/archethic_web/router.ex
Labels: feature, API

#570 Support UTXO & Tx Inputs streaming
  lib/archethic.ex
  lib/archethic/mining/transaction_context.ex
  lib/archethic/networking/ip_lookup.ex
  lib/archethic/p2p/message.ex
  lib/archethic/p2p/message/get_transaction_inputs.ex
  lib/archethic/p2p/message/get_unspent_outputs.ex
  lib/archethic/p2p/message/transaction_input_list.ex
  lib/archethic/p2p/message/unspent_output_list.ex
  lib/archethic/replication/transaction_context.ex
  lib/archethic/transaction_chain.ex
  lib/archethic_web/graphql_schema.ex
  lib/archethic_web/graphql_schema/integer_type.ex
  lib/archethic_web/graphql_schema/page_type.ex
  lib/archethic_web/graphql_schema/resolver.ex
  lib/archethic_web/graphql_schema/transaction_type.ex
  lib/archethic_web/live/transaction_details_live.ex
  test/archethic/transaction_chain_test.exs
  test/archethic_test.exs
Labels: feature, P2P, mining, UI, API

#574 Improve node availability
  lib/archethic/beacon_chain/slot.ex
  lib/archethic/beacon_chain/slot_timer.ex
  lib/archethic/beacon_chain/subset.ex
  lib/archethic/beacon_chain/subset/p2p_sampling.ex
  lib/archethic/beacon_chain/summary.ex
  lib/archethic/p2p/client.ex
  lib/archethic/p2p/client/connection.ex
  lib/archethic/p2p/client/default_impl.ex
  lib/archethic/p2p/listener_protocol.ex
  lib/archethic/utils.ex
  test/archethic/beacon_chain/slot_timer_test.exs
  test/archethic/beacon_chain/subset/p2p_sampling_test.exs
  test/archethic/beacon_chain/subset/summary_cache_test.exs
  test/archethic/beacon_chain/subset_test.exs
  test/archethic/p2p/client/connection_test.exs
Labels: bug, beacon chain, core team

#573 Add last transactions feed on the homepage #404
  lib/archethic_web/live/chains/beacon_live.ex
  lib/archethic_web/live/explorer/cache.ex
  lib/archethic_web/live/explorer_index_live.ex
  lib/archethic_web/live/top_transactions_component.ex
  lib/archethic_web/supervisor.ex
  lib/archethic_web/templates/explorer/index.html.leex
Labels: feature, UI

#575 [Feature] Node rewards chain explorer. Resolves [#413]
  .gitignore
  lib/archethic/bootstrap.ex
  lib/archethic/bootstrap/network_constraints.ex
  lib/archethic/crypto.ex
  lib/archethic/db.ex
  lib/archethic/db/embedded_impl.ex
  lib/archethic/db/embedded_impl/chain_index.ex
  lib/archethic/mining/pending_transaction_validation.ex
  lib/archethic/oracle_chain.ex
  lib/archethic/reward.ex
  lib/archethic/shared_secrets.ex
  lib/archethic/transaction_chain.ex
  lib/archethic_web/live/chains/reward_live.ex
  lib/archethic_web/router.ex
  lib/archethic_web/templates/explorer/beacon_chain_index.html.leex
  lib/archethic_web/templates/explorer/oracle_chain_index.html.leex
  lib/archethic_web/templates/explorer/reward_chain_index.html.leex
  lib/archethic_web/templates/layout/root.html.eex
  test/archethic/db/embedded_impl_test.exs
  test/archethic_web/controllers/faucet_controller_test.exs
  test/archethic_web/live/rewards_live_test.exs
Labels: UI, DB, core team

#585 Support AEWeb certificates
  config/dev.exs
  config/prod.exs
  lib/archethic_web/controllers/api/web_hosting_controller.ex
  lib/archethic_web/controllers/root_controller.ex
  lib/archethic_web/domain.ex
  mix.exs
  mix.lock
  priv/cert/selfsigned.pem
  priv/cert/selfsigned_key.pem
  test/archethic_web/controllers/api/web_hosting_controller_test.exs
Labels: feature, system, web hosting

#581 [Feature] Add node shared secrets chain explorer#411
  lib/archethic/db/embedded_impl/chain_index.ex
  lib/archethic_web/live/chains/node_shared_secrets_live.ex
  lib/archethic_web/live/chains/reward_live.ex
  lib/archethic_web/router.ex
  lib/archethic_web/templates/explorer/node_shared_secrets_chain_index.html.leex
  lib/archethic_web/templates/layout/root.html.eex
  lib/archethic_web/web_utils.ex
  test/archethic_web/live/rewards_live_test.exs
Labels: UI

#587 Add origin chain explorer #412
  lib/archethic/shared_secrets.ex
  lib/archethic_web/live/chains/origin_live.ex
  lib/archethic_web/router.ex
  lib/archethic_web/templates/explorer/origin_chain_index.html.leex
  lib/archethic_web/templates/layout/root.html.eex
Labels: UI
