Repository archethic-foundation/archethic-node, pull requests merged in 2022-11, with the labels that each got.

#666 Handle ipv6 local ip in node settings page
  lib/archethic_web/live/settings_live.ex
Labels: bug, UI

#667 Add lower timeout for replication error notification
  lib/archethic/mining.ex
Labels: bug, mining

#669 Update installation and release scripts to use asdf
  scripts/install.sh
  scripts/release.sh
Labels: dependencies, enhancements

#676 CrossValidation check Proof Of Work is authorized
  lib/archethic/mining/validation_context.ex
  test/archethic/mining/validation_context_test.exs
Labels: bug, mining

#672 Optimize ack of previous shards
  lib/archethic/mining/distributed_workflow.ex
  lib/archethic/mining/standalone_workflow.ex
  lib/archethic/p2p/message.ex
  lib/archethic/p2p/message/notify_last_transaction_address.ex
  lib/archethic/replication.ex
  test/archethic/p2p/messages_test.exs
  test/archethic/replication_test.exs
Labels: bug, core team, replication

#679 Fix genesis pool amounts & addresses
  config/prod.exs
Labels: bug, bootstrap

#683 Use current node view for downloading while in self repair
  lib/archethic/beacon_chain.ex
  lib/archethic/replication.ex
  lib/archethic/replication/transaction_context.ex
  lib/archethic/self_repair/sync.ex
  lib/archethic/self_repair/sync/transaction_handler.ex
  lib/archethic_web/live/chains/beacon_live.ex
  test/archethic/beacon_chain_test.exs
  test/archethic/replication/transaction_context_test.exs
  test/archethic/self_repair/sync/transaction_handler_test.exs
  test/archethic/self_repair/sync_test.exs
Labels: bug, self repair, bootstrap

#685 Improve Task's timeout handling
  lib/archethic/beacon_chain.ex
  lib/archethic/beacon_chain/subset.ex
Labels: beacon chain, enhancements

#681 Fix Proof of work existence for node transaction
  lib/archethic/mining/validation_context.ex
Labels: bug, mining, core team

#690 Add @vsn attribute to GenServers
  lib/archethic/account/mem_tables/token_ledger.ex
  lib/archethic/account/mem_tables/uco_ledger.ex
  lib/archethic/account/mem_tables_loader.ex
  lib/archethic/beacon_chain/slot_timer.ex
  lib/archethic/beacon_chain/subset.ex
  lib/archethic/beacon_chain/subset/summary_cache.ex
  lib/archethic/beacon_chain/summary_timer.ex
  lib/archethic/beacon_chain/update.ex
  lib/archethic/contracts/loader.ex
  lib/archethic/contracts/transaction_lookup.ex
  lib/archethic/contracts/worker.ex
  lib/archethic/crypto/ed25519/libsodium_port.ex
  lib/archethic/crypto/keystore/node/origin/software_impl.ex
  lib/archethic/crypto/keystore/node/origin/tpm_impl.ex
  lib/archethic/crypto/keystore/node/software_impl.ex
  lib/archethic/crypto/keystore/shared_secrets/software_impl.ex
  lib/archethic/db/embedded_impl/bootstrap_info.ex
  lib/archethic/db/embedded_impl/chain_index.ex
  lib/archethic/db/embedded_impl/chain_writer.ex
  lib/archethic/db/embedded_impl/p2p_view.ex
  lib/archethic/db/embedded_impl/stats_info.ex
  lib/archethic/election/constraints.ex
  lib/archethic/election/hypergeometric_distribution.ex
  lib/archethic/governance/pools/mem_table_loader.ex
  lib/archethic/metrics/ets_flush.ex
  lib/archethic/metrics/poller.ex
  lib/archethic/mining/distributed_workflow.ex
  lib/archethic/mining/standalone_workflow.ex
  lib/archethic/networking/scheduler.ex
  lib/archethic/oracle_chain/mem_table.ex
  lib/archethic/oracle_chain/mem_table_loader.ex
  lib/archethic/oracle_chain/scheduler.ex
  lib/archethic/p2p/bootstrapping_seeds.ex
  lib/archethic/p2p/client/connection.ex
  lib/archethic/p2p/geo_patch/geo_ip/maxmind_db.ex
  lib/archethic/p2p/listener.ex
  lib/archethic/p2p/mem_table.ex
  lib/archethic/p2p/mem_table_loader.ex
  lib/archethic/reward/mem_tables/reward_tokens.ex
  lib/archethic/reward/mem_tables_loader.ex
  lib/archethic/reward/scheduler.ex
  lib/archethic/self_repair/notifier.ex
  lib/archethic/self_repair/scheduler.ex
  lib/archethic/shared_secrets/mem_tables/network_lookup.ex
  lib/archethic/shared_secrets/mem_tables/origin_key_lookup.ex
  lib/archethic/shared_secrets/mem_tables_loader.ex
  lib/archethic/shared_secrets/node_renewal_scheduler.ex
  lib/archethic/transaction_chain/mem_tables/ko_ledger.ex
  lib/archethic/transaction_chain/mem_tables/pending_ledger.ex
  lib/archethic/transaction_chain/mem_tables_loader.ex
  lib/archethic/utils/detect_node_responsiveness.ex
  lib/archethic/utils/job_cache.ex
  lib/archethic/utils/job_conductor.ex
  lib/archethic/utils/port_handler.ex
  lib/archethic/utils/regression/benchmarks/seed_holder.ex
  lib/archethic_web/faucet_rate_limiter.ex
  lib/archethic_web/live/chains/cache.ex
  lib/archethic_web/live/explorer/cache.ex
  lib/archethic_web/transaction_subscriber.ex
Labels: feature

#688 Fix recursion of notify last address
  lib/archethic/mining/distributed_workflow.ex
  lib/archethic/mining/standalone_workflow.ex
  lib/archethic/mining/validation_context.ex
  lib/archethic/p2p/message.ex
  lib/archethic/p2p/message/notify_last_transaction_address.ex
  lib/archethic/p2p/message/notify_previous_chain.ex
  lib/archethic/replication.ex
  test/archethic/p2p/messages_test.exs
  test/archethic/replication_test.exs
Labels: bug, P2P, replication

#691 Add default `code_change/4` in GenStateMachine
  lib/archethic/mining/distributed_workflow.ex
  lib/archethic/oracle_chain/scheduler.ex
  lib/archethic/p2p/client/connection.ex
  lib/archethic/reward/scheduler.ex
  lib/archethic/shared_secrets/node_renewal_scheduler.ex
Labels: system, enhancements

#674 Ensure destination of elected message
  lib/archethic/beacon_chain/replication_attestation.ex
  lib/archethic/beacon_chain/slot/validation.ex
  lib/archethic/beacon_chain/subset.ex
  lib/archethic/beacon_chain/summary_aggregate.ex
  lib/archethic/p2p/client/default_impl.ex
  lib/archethic/p2p/listener_protocol.ex
  lib/archethic/p2p/message.ex
  lib/archethic/utils/regression.ex
  test/archethic/beacon_chain_test.exs
Labels: P2P, core team, enhancements

#704 :bug: add quorum for requesting balance
  lib/archethic.ex
  test/archethic_test.exs
Labels: feature, P2P

#706 :racehorse: remove old daily keys from ets table
  lib/archethic/crypto/keystore/shared_secrets/software_impl.ex
  test/archethic/crypto/keystore/shared_secrets/software_impl_test.exs
Labels: shared secrets, enhancements

#684 Move inputs from ETS to disk
  lib/archethic/account/mem_tables/token_ledger.ex
  lib/archethic/account/mem_tables/uco_ledger.ex
  lib/archethic/db.ex
  lib/archethic/db/embedded_impl.ex
  lib/archethic/db/embedded_impl/chain_reader.ex
  lib/archethic/db/embedded_impl/inputs_reader.ex
  lib/archethic/db/embedded_impl/inputs_writer.ex
  lib/archethic/transaction_chain.ex
  test/archethic/account/mem_tables/token_ledger_test.exs
  test/archethic/account/mem_tables/uco_ledger_test.exs
  test/archethic/account/mem_tables_loader_test.exs
  test/archethic/account_test.exs
  test/archethic/db/embedded_impl/inputs_test.exs
  test/archethic/transaction_chain/transaction/input_test.exs
  test/support/template.ex
Labels: feature, DB

#707 add graphql query to get version of running code, protocol and transaction
  lib/archethic_web/graphql_schema.ex
  lib/archethic_web/graphql_schema/resolver.ex
  lib/archethic_web/graphql_schema/version_type.ex
  test/archethic_web/graphql_schema_test.exs
Labels: feature, API

#717 Update last transaction address only if timestamp is greater
  lib/archethic/db/embedded_impl/chain_index.ex
  test/archethic/db/embedded_impl/chain_index_test.exs
  test/archethic/db/embedded_impl_test.exs
Labels: bug, DB, core team

#709 compute node reward based on scheduler time
  lib/archethic/reward.ex
  lib/archethic/utils.ex
Labels: bug, core team, rewards

#723 GraphQL: return token.ownerships
  lib/archethic_web/graphql_schema/resolver.ex
  lib/archethic_web/graphql_schema/transaction_type.ex
  test/archethic_web/graphql_schema_test.exs
Labels: API

#722 Ensure there is never more validation nodes than storage nodes
  lib/archethic/election.ex
  test/archethic/election_test.exs
  test/archethic_test.exs
Labels: mining, core team, enhancements

#715 Valid the authorized nodes in the node shared secret
  lib/archethic/mining/pending_transaction_validation.ex
  test/archethic/mining/pending_transaction_validation_test.exs
  test/archethic/shared_secrets/node_renewal_test.exs
Labels: bug, shared secrets, core team

#705 AEWeb - Directory listing
  config/dev.exs
  config/prod.exs
  config/test.exs
  lib/archethic_web/controllers/aeweb_root_controller.ex
  lib/archethic_web/controllers/api/web_hosting_controller.ex
  lib/archethic_web/templates/dir_listing/index.html.heex
  lib/archethic_web/views/dir_listing_view.ex
  test/archethic_web/controllers/api/web_hosting_controller_test.exs
Labels: feature, core team
