Repository archethic-foundation/archethic-node, pull requests merged in 2022-05, with the labels that each got.

#294 Fix beacon summary aggregate
  lib/archethic/beacon_chain/summary_timer.ex
  lib/archethic/self_repair/sync.ex
  lib/archethic/self_repair/sync/beacon_aggregate.ex
  lib/archethic/self_repair/sync/beacon_summary_handler.ex
  lib/mix/tasks/clean_db.ex
  test/archethic/beacon_chain/summary_timer_test.exs
Labels: bug, self-repair

#267 Benchmark single transfer per node
  assets/js/socket.js
  assets/package-lock.json
  lib/archethic/mining/validation_context.ex
  lib/archethic/replication/transaction_validator.ex
  lib/archethic/transaction_chain/transaction.ex
  lib/archethic/transaction_chain/transaction/validation_stamp/ledger_operations.ex
  lib/archethic/utils/regression.ex
  lib/archethic/utils/regression/benchmarks/end_to_end_validation.ex
  lib/archethic/utils/regression/benchmarks/seed_holder.ex
  lib/archethic/utils/regression/playbook.ex
  lib/archethic/utils/websocket/client.ex
  lib/archethic/utils/websocket/handler.ex
  lib/archethic/utils/websocket/supervisor.ex
  mix.exs
  mix.lock
Labels: feature, system, testing, core team

#292 Origin key api
  config/config.exs
  lib/archethic/shared_secrets.ex
  lib/archethic/utils/regression/playbook.ex
  lib/archethic_web/controllers/api/origin_key_controller.ex
  lib/archethic_web/router.ex
  test/archethic_web/controllers/api/origin_key_controller_test.exs
  test/archethic_web/controllers/api/transaction_controller_test.exs
Labels: feature, crypto, API, shared-secrets

#298 Format UCO's amount in the chain UI
  lib/archethic_web/templates/explorer/chain.html.eex
Labels: bug, UI

#301 Correct playbook origin key error
  lib/archethic/utils/regression/playbook.ex
Labels: bug, shared-secrets, testing

#307 Correct India coordinates on map
  assets/static/worldmap.json
Labels: bug, UI

#309 Improve GitHub actions duration
  .github/workflows/ci.yml
  .gitignore
  mix.exs
  test/archethic/beacon_chain_test.exs
  test/archethic/bootstrap/sync_test.exs
  test/archethic/oracle_chain/scheduler_test.exs
  test/archethic/self_repair/sync/beacon_summary_handler_test.exs
  test/archethic/shared_secrets/node_renewal_scheduler_test.exs
Labels: testing

#312 Correct CrossValidate message error
  lib/archethic/p2p/message.ex
Labels: bug, P2P

#311 Hybrid root of trust
  config/dev.exs
  config/prod.exs
  config/test.exs
  lib/archethic/bootstrap/network_init.ex
  lib/archethic/bootstrap/transaction_handler.ex
  lib/archethic/crypto.ex
  lib/archethic/crypto/keystore/node.ex
  lib/archethic/crypto/keystore/node/origin.ex
  lib/archethic/crypto/keystore/node/origin/software_impl.ex
  lib/archethic/crypto/keystore/node/origin/tpm_impl.ex
  lib/archethic/crypto/keystore/node/software_impl.ex
  lib/archethic/crypto/keystore/node/tpm_impl.ex
  lib/archethic/crypto/keystore/node_supervisor.ex
  lib/archethic/crypto/keystore/supervisor.ex
  lib/archethic/mining/pending_transaction_validation.ex
  lib/archethic/mining/proof_of_work.ex
  lib/archethic/networking/scheduler.ex
  lib/archethic/p2p/mem_table.ex
  lib/archethic/p2p/mem_table_loader.ex
  lib/archethic/p2p/node.ex
  lib/archethic/shared_secrets/mem_tables_loader.ex
  lib/archethic/transaction_chain/transaction.ex
  lib/archethic_web/graphql_schema/p2p_type.ex
  lib/archethic_web/graphql_schema/resolver.ex
  lib/archethic_web/views/explorer_view.ex
  test/archethic/bootstrap/sync_test.exs
  test/archethic/bootstrap/transaction_handler_test.exs
  test/archethic/crypto/keystore/node/origin/software_impl_test.exs
  test/archethic/crypto/keystore/node/origin/tpm_impl_test.exs
  test/archethic/crypto/keystore/node/software_impl_test.exs
  test/archethic/crypto/keystore/node/tpm_impl_test.exs
  test/archethic/mining/distributed_workflow_test.exs
  test/archethic/mining/pending_transaction_validation_test.exs
  test/archethic/mining/validation_context_test.exs
  test/archethic/p2p/bootstrapping_seeds_test.exs
  test/archethic/p2p/mem_table_loader_test.exs
  test/archethic/p2p/messages_test.exs
  test/archethic/replication_test.exs
  test/archethic/self_repair/sync/beacon_summary_handler_test.exs
  test/archethic/shared_secrets/mem_tables_loader_test.exs
  test/archethic/transaction_chain/transaction/cross_validation_stamp_test.exs
  test/archethic/transaction_chain/transaction/validation_stamp_test.exs
  test/archethic/transaction_chain/transaction_test.exs
  test/archethic_web/graphql_schema_test.exs
  test/support/template.ex
  test/support/transaction_factory.ex
  test/test_helper.exs
Labels: crypto, breaking-change

#316 Fix chunk authorized nodes issue
  lib/archethic/crypto.ex
  lib/archethic/crypto/keystore/shared_secrets/software_impl.ex
  lib/archethic/p2p/mem_table_loader.ex
  test/archethic/p2p/mem_table_loader_test.exs
Labels: bug, P2P, crypto

#314 297 Pagination based on paging_state as last page last transaction address GraphQl API
  lib/archethic.ex
  lib/archethic_web/graphql_schema.ex
  lib/archethic_web/graphql_schema/page_type.ex
  lib/archethic_web/graphql_schema/resolver.ex
  test/archethic_web/controllers/api/transaction_controller_test.exs
  test/archethic_web/graphql_schema_test.exs
Labels: feature, API, breaking-change

#322 Fix renaming of ArchEthic to Archethic
  .iex.exs
  rel/commands/regression_test
  scripts/release.sh
  test/archethic/governance/0001-CI-Pass.patch
Labels: bug, testing

#325 Self repair on transfert transaction
  lib/archethic/db/embedded_impl/chain_index.ex
  lib/archethic/db/embedded_impl/chain_reader.ex
  lib/archethic/p2p/message.ex
  lib/archethic/p2p/message/get_transaction_chain.ex
  lib/archethic/reward.ex
  test/archethic/db/embedded_impl_test.exs
  test/archethic/p2p/messages_test.exs
Labels: bug, self-repair

#334 Resolves Add telemetry for embedded database#327
  lib/archethic/db/embedded_impl/chain_reader.ex
  lib/archethic/db/embedded_impl/chain_writer.ex
Labels: feature, DB

#337 New api for web hosting
  lib/archethic_web/controllers/api/web_hosting_controller.ex
  lib/archethic_web/router.ex
  lib/archethic_web/views/explorer_view.ex
  mix.exs
  mix.lock
  test/archethic_web/controllers/api/web_hosting_controller_test.exs
Labels: feature, API

#342 Mix task nat discovery port forwarding#341
  lib/archethic/networking/port_forwarding.ex
  lib/mix/tasks/nettools.ex
  mix.exs
Labels: feature, good first issue, P2P
