Repository archethic-foundation/archethic-node, pull requests merged in 2022-02, with the labels that each got.

#219 Use a FSM in the OracleChain Scheduler
  lib/archethic/oracle_chain/scheduler.ex
  test/archethic/oracle_chain/scheduler_test.exs
Labels: OracleChain

#205 [Feature] Metric Dashboard PR2
  assets/js/app.js
  assets/js/metric_config.js
  assets/package-lock.json
  assets/package.json
  lib/archethic/application.ex
  lib/archethic/metrics/helpers.ex
  lib/archethic/metrics/metric_supervisor.ex
  lib/archethic/metrics/parser.ex
  lib/archethic/metrics/poller.ex
  lib/archethic/p2p/client/connection.ex
  lib/archethic_web/live/dashboard_live.ex
  lib/archethic_web/live/explorer_index_live.ex
  lib/archethic_web/router.ex
  lib/archethic_web/templates/dashboard/dashboard.html.leex
  lib/archethic_web/templates/explorer/index.html.leex
  lib/archethic_web/templates/layout/root.html.eex
  lib/archethic_web/views/dashboard_view.ex
Labels: enhancement

#210 Prepend curve type in address
  config/dev.exs
  config/prod.exs
  config/test.exs
  docker-compose.yml
  lib/archethic/account/mem_tables_loader.ex
  lib/archethic/beacon_chain.ex
  lib/archethic/beacon_chain/slot.ex
  lib/archethic/beacon_chain/slot/transaction_summary.ex
  lib/archethic/beacon_chain/summary.ex
  lib/archethic/bootstrap.ex
  lib/archethic/crypto.ex
  lib/archethic/crypto/id.ex
  lib/archethic/mining/pending_transaction_validation.ex
  lib/archethic/p2p.ex
  lib/archethic/p2p/message.ex
  lib/archethic/p2p/node.ex
  lib/archethic/release_task.ex
  lib/archethic/self_repair/sync/beacon_summary_handler/transaction_handler.ex
  lib/archethic/shared_secrets/node_renewal.ex
  lib/archethic/transaction_chain.ex
  lib/archethic/transaction_chain/transaction.ex
  lib/archethic/transaction_chain/transaction/data.ex
  lib/archethic/transaction_chain/transaction/validation_stamp/ledger_operations.ex
  lib/archethic/utils/regression/benchmarks/p2p_message.ex
  lib/archethic/utils/regression/playbook.ex
  lib/archethic/utils/regression/playbooks/smart_contract.ex
  lib/archethic/utils/regression/playbooks/uco.ex
  lib/archethic_web/controllers/faucet_controller.ex
  test/archethic/beacon_chain/subset_test.exs
  test/archethic/beacon_chain_test.exs
  test/archethic/bootstrap/network_init_test.exs
  test/archethic/bootstrap/sync_test.exs
  test/archethic/bootstrap_test.exs
  test/archethic/contracts/loader_test.exs
  test/archethic/contracts/worker_test.exs
  test/archethic/mining/distributed_workflow_test.exs
  test/archethic/mining/pending_transaction_validation_test.exs
  test/archethic/p2p/mem_table_loader_test.exs
  test/archethic/p2p/messages_test.exs
  test/archethic/self_repair/sync/beacon_summary_handler_test.exs
  test/archethic/self_repair/sync_test.exs
  test/archethic/shared_secrets/mem_tables_loader_test.exs
  test/archethic/transaction_chain/transaction_test.exs
Labels: Crypto

#234 Indicate usd price near of uco amounts #226
  lib/archethic_web/controllers/explorer_controller.ex
  lib/archethic_web/live/transaction_details_live.ex
  lib/archethic_web/templates/explorer/chain.html.eex
  lib/archethic_web/templates/explorer/transaction_details.html.leex
  lib/archethic_web/views/layout_helpers.ex
Labels: enhancement, UI, external contribution
