Repository archethic-foundation/archethic-node, pull requests merged in 2022-03, with the labels that each got.

#251 [Feature] Add on_chain_wallet origin id
  lib/archethic/account/mem_tables_loader.ex
  lib/archethic/crypto.ex
  lib/archethic/crypto/id.ex
  lib/archethic/election.ex
  lib/archethic/shared_secrets/mem_tables/network_lookup.ex
  lib/archethic/shared_secrets/mem_tables_loader.ex
  lib/archethic/transaction_chain/transaction/data/ownership.ex
  lib/archethic/utils/testnet.ex
  test/archethic/beacon_chain_test.exs
  test/archethic/crypto_test.exs
  test/archethic/election_test.exs
  test/archethic/self_repair/sync_test.exs
  test/archethic/shared_secrets/mem_tables_loader_test.exs
Labels: feature

#252 Fix crypto identifiers bootstrap
  config/dev.exs
  docker-compose.yml
Labels: bug

#262 Add http port in node details
  .gitignore
  lib/archethic/application.ex
  lib/archethic/bootstrap.ex
  lib/archethic/bootstrap/sync.ex
  lib/archethic/bootstrap/transaction_handler.ex
  lib/archethic/metrics/collector.ex
  lib/archethic/metrics/collector/metrics_endpoint.ex
  lib/archethic/metrics/poller.ex
  lib/archethic/mining/pending_transaction_validation.ex
  lib/archethic/networking/scheduler.ex
  lib/archethic/p2p/bootstrapping_seeds.ex
  lib/archethic/p2p/mem_table.ex
  lib/archethic/p2p/mem_table_loader.ex
  lib/archethic/p2p/node.ex
  lib/archethic_web/views/explorer_view.ex
  test/archethic/bootstrap/sync_test.exs
  test/archethic/bootstrap/transaction_handler_test.exs
  test/archethic/bootstrap_test.exs
  test/archethic/db/cassandra_impl_test.exs
  test/archethic/metrics/poller_test.exs
  test/archethic/mining/distributed_workflow_test.exs
  test/archethic/mining/pending_transaction_validation_test.exs
  test/archethic/p2p/bootstrapping_seeds_test.exs
  test/archethic/p2p/mem_table_loader_test.exs
  test/archethic/p2p/messages_test.exs
  test/archethic/self_repair/sync/beacon_summary_handler_test.exs
Labels: P2P, serialization
