Repository archethic-foundation/archethic-node, pull requests merged in 2023-12, with the labels that each got.

#1338 Default RPC Timeout to 30s
  lib/archethic_web/api/jsonrpc/controllers/jsonrpc_controller.ex
Labels: bug

#1345 Consensus error due to wrong timestamp used
  lib/archethic/mining/validation_context.ex
  test/archethic/mining/validation_context_test.exs
Labels: bug, mining

#1347 Utils.run_exclusive doesn't not send messages anymore
  lib/archethic/utils.ex
  test/archethic/utils_test.exs
Labels: bug

#1352 Remove CoinMarketCap Uniris Oracle
  config/config.exs
  lib/archethic/oracle_chain/services/uco_price/providers/coin_marketcap_uniris.ex
  test/archethic/oracle_chain/services/uco_price/coin_marketcap_test.exs
Labels: oracle chain, enhancements

#1354 Fix sort of nodes during election's refinement
  lib/archethic/election.ex
Labels: bug, mining, election

#1333 Dashboard does not use metrics anymore
  .formatter.exs
  assets/js/app.js
  assets/js/metric_config.js
  config/test.exs
  lib/archethic/metrics/collector.ex
  lib/archethic/metrics/collector/metrics_endpoint.ex
  lib/archethic/metrics/metric_supervisor.ex
  lib/archethic/metrics/parser.ex
  lib/archethic/metrics/poller.ex
  lib/archethic/mining/distributed_workflow.ex
  lib/archethic/mining/standalone_workflow.ex
  lib/archethic/p2p/message.ex
  lib/archethic/p2p/message/dashboard_data.ex
  lib/archethic/p2p/message/get_dashboard_data.ex
  lib/archethic/p2p/message/message_id.ex
  lib/archethic/pub_sub.ex
  lib/archethic/utils.ex
  lib/archethic_web/dashboard_metrics.ex
  lib/archethic_web/dashboard_metrics_aggregator.ex
  lib/archethic_web/explorer/live/dashboard_live.ex
  lib/archethic_web/explorer/templates/dashboard/dashboard.html.heex
  lib/archethic_web/supervisor.ex
  priv/static/cache_manifest.json
  test/archethic/metrics/collector_test.exs
  test/archethic/metrics/parser_test.exs
  test/archethic/metrics/poller_test.exs
  test/archethic/p2p/message/dashboard_data_test.exs
  test/archethic/p2p/message/get_dashboard_data_test.exs
  test/archethic_web/dashboard_metrics_aggregator_test.exs
  test/archethic_web/dashboard_metrics_test.exs
  test/test_helper.exs
Labels: enhancements

#1355 Utils.time_offset is more accurate
  lib/archethic/beacon_chain/slot_timer.ex
  lib/archethic/beacon_chain/summary_timer.ex
  lib/archethic/contracts/worker.ex
  lib/archethic/networking/scheduler.ex
  lib/archethic/oracle_chain.ex
  lib/archethic/oracle_chain/scheduler.ex
  lib/archethic/oracle_chain/services/hydrating_cache.ex
  lib/archethic/reward/scheduler.ex
  lib/archethic/self_repair.ex
  lib/archethic/self_repair/scheduler.ex
  lib/archethic/shared_secrets/node_renewal_scheduler.ex
  lib/archethic/utils.ex
Labels: bug

#1327 GetNetworkStats improvment: timeout & caching
  config/test.exs
  lib/archethic/application.ex
  lib/archethic/beacon_chain/network_coordinates.ex
  lib/archethic/beacon_chain/subset.ex
  lib/archethic/beacon_chain/subset/stats_collector.ex
  lib/archethic/beacon_chain/subset/summary_cache.ex
  lib/archethic/beacon_chain/subset/supervisor.ex
  lib/archethic/p2p/message/get_network_stats.ex
  lib/archethic/pub_sub.ex
  lib/archethic/self_repair/scheduler.ex
  lib/archethic/utils/job_cache.ex
  test/archethic/beacon_chain/network_coordinates_test.exs
  test/archethic/beacon_chain/subset/stats_collector_test.exs
  test/archethic/beacon_chain/subset/summary_cache_test.exs
  test/archethic/beacon_chain/subset_test.exs
  test/archethic/p2p/message/get_network_stats_test.exs
  test/archethic/utils/job_cache_test.exs
Labels: bug, beacon chain, enhancements

#1357 Fix paging state
  lib/archethic/transaction_chain.ex
  test/archethic/transaction_chain_test.exs
Labels: bug
