Repository archethic-foundation/archethic-node, pull requests merged in 2023-11, with the labels that each got.

#1313 Fix aeweb referer
  lib/archethic_web/explorer/controllers/explorer_root_controller.ex
Labels: bug, web hosting

#1317 Fix serialization issue on state utxo
  lib/archethic/db/embedded_impl/encoding.ex
  lib/archethic/p2p/message/get_unspent_outputs.ex
  lib/archethic/p2p/message/unspent_output_list.ex
  lib/archethic/transaction_chain/transaction/validation_stamp/ledger_operations/unspent_output.ex
  lib/archethic/transaction_chain/transaction/validation_stamp/ledger_operations/versioned_unspent_output.ex
  lib/archethic/transaction_chain/transaction_summary.ex
  lib/archethic_web/explorer/live/transaction_details_live.ex
Labels: bug, serialization

#1322 NetworkSync.validate_address ask more nodes about the latest address
  lib/archethic.ex
  lib/archethic/p2p.ex
  lib/archethic/self_repair/network_chain.ex
  lib/archethic/transaction_chain.ex
  test/archethic/p2p_test.exs
  test/archethic/self_repair/network_chain_test.exs
  test/archethic/transaction_chain_test.exs
  test/archethic_test.exs
Labels: bug

#1329 Coinmarketcap provider duplication
  config/config.exs
  lib/archethic/oracle_chain/services/uco_price/providers/coin_marketcap_archethic.ex
  lib/archethic/oracle_chain/services/uco_price/providers/coin_marketcap_uniris.ex
  test/archethic/oracle_chain/services/uco_price/coin_marketcap_test.exs
Labels: bug
