Repository archethic-foundation/archethic-node, pull requests merged in 2024-03, with the labels that each got.

#1445 AEIP-21-P2: New genesis node SC Worker
  lib/archethic.ex
  lib/archethic/beacon_chain/slot_timer.ex
  lib/archethic/contracts.ex
  lib/archethic/contracts/contract.ex
  lib/archethic/contracts/interpreter/action_interpreter.ex
  lib/archethic/contracts/interpreter/library/common/chain_impl.ex
  lib/archethic/contracts/loader.ex
  lib/archethic/contracts/worker.ex
  lib/archethic/db.ex
  lib/archethic/db/embedded_impl.ex
  lib/archethic/election.ex
  lib/archethic/mining/smart_contract_validation.ex
  lib/archethic/mining/validation_context.ex
  lib/archethic/p2p/message/get_unspent_outputs.ex
  lib/archethic/p2p/message/notify_last_transaction_address.ex
  lib/archethic/p2p/message/validate_smart_contract_call.ex
  lib/archethic/replication.ex
  lib/archethic/replication/transaction_context.ex
  lib/archethic/replication/transaction_validator.ex
  lib/archethic/self_repair.ex
  lib/archethic/transaction_chain.ex
  lib/archethic/transaction_chain/transaction/validation_stamp/ledger_operations/versioned_unspent_output.ex
  lib/archethic/transaction_chain/transaction_input.ex
  lib/archethic/utils/detect_node_responsiveness.ex
  lib/archethic/utils/regression/api.ex
  lib/archethic/utils/regression/playbooks/smart_contract.ex
  lib/archethic/utils/regression/playbooks/smart_contract/counter.ex
  lib/archethic_web/api/graphql/schema.ex
  lib/archethic_web/api/graphql/schema/resolver.ex
  lib/archethic_web/explorer/live/chains/transaction_chain_live.ex
  lib/archethic_web/explorer/live/settings_live.ex
  test/archethic/contracts/contract_test.exs
  test/archethic/contracts/interpreter/library/common/chain_test.exs
  test/archethic/contracts/loader_test.exs
  test/archethic/contracts/worker_test.exs
  test/archethic/election_test.exs
  test/archethic/mining/smart_contract_validation_test.exs
  test/archethic/p2p/message/get_unspent_outputs_test.exs
  test/archethic/replication/transaction_context_test.exs
  test/archethic/replication/transaction_validator_test.exs
  test/archethic/replication_test.exs
  test/archethic/transaction_chain_test.exs
  test/support/template.ex
  test/support/transaction_factory.ex
Labels: feature, smart contracts, AEIP

#1448 Release/1.5.0 rc1
  lib/archethic/contracts/loader.ex
  lib/archethic/transaction_chain/transaction/validation_stamp/ledger_operations.ex
  mix.exs
  rel/appups/archethic/1.4.8_to_1.5.0-rc1.appup
  test/archethic/transaction_chain/transaction/validation_stamp/ledger_operations_test.exs
Labels: release

#1450 Fix TransactionInput.set_spent to compare only using from and type
  lib/archethic/transaction_chain/transaction_input.ex
Labels: bug

#1451 Improve UTXO streamning using :ets.lookup for memory UTXOs retrieval
  lib/archethic/utxo.ex
  lib/archethic/utxo/memory_ledger.ex
  test/archethic/utxo/loader_test.exs
  test/archethic/utxo/memory_ledger_test.exs
  test/archethic/utxo_test.exs
Labels: DB, enhancements

#1452 Fix get balance when amount is nil on the chain page
  lib/archethic_web/explorer/live/chains/transaction_chain_live.ex
Labels: bug, UI

#1453 Fix migration to store inputs as the next address validation inputs
  priv/migration_tasks/prod/1.5.0@aeip_21-2.exs
Labels: bug, DB

#1456 feat ✨: Cache smart contract call validation
  lib/archethic/p2p/message/validate_smart_contract_call.ex
  lib/archethic/utils/job_cache.ex
  test/archethic/p2p/message/validate_smart_contract_call_test.exs
Labels: smart contracts, mining

#1457 feat ✨ (db): Add tool to interact with DB + cleaning tasks
  Makefile
  lib/archethic/utxo.ex
  lib/archethic/utxo/db_ledger/file_impl.ex
  lib/mix/tasks/db.ex
  rel/commands/db
  rel/config.exs
Labels: feature, DB

#1458 Refactor Worker as GenStateMachine, add Invalid call management
  lib/archethic/contracts/loader.ex
  lib/archethic/contracts/worker.ex
  test/archethic/contracts/loader_test.exs
  test/archethic/contracts/worker_test.exs
  test/support/template.ex
Labels: feature, smart contracts

#1459 Add consumed_utxo control also for recipient
  lib/archethic/utxo.ex
  test/archethic/contracts/worker_test.exs
Labels: bug, replication

#1461 Up version 1.5.0-rc3
  mix.exs
  rel/appups/archethic/1.5.0-rc2_to_1.5.0-rc3.appup
Labels: release

#1465 Fix genesis nodes Election for UTXO and SC call
  lib/archethic/mining/smart_contract_validation.ex
  lib/archethic/replication/transaction_context.ex
Labels: bug, election

#1466 Add last_chain_sync_date in GetBalance message
  lib/archethic.ex
  lib/archethic/p2p/message/balance.ex
  lib/archethic/p2p/message/get_balance.ex
  test/archethic/p2p/client/connection_test.exs
  test/archethic/p2p/message/get_unspent_outputs_test.exs
  test/archethic/p2p/messages_test.exs
  test/archethic/transaction_chain_test.exs
  test/archethic_test.exs
Labels: bug, P2P

#1467 Fix Archethic.get_balance to prefer UTXO list over aggregated balance
  lib/archethic.ex
  lib/archethic/contracts/interpreter/library/common/chain_impl.ex
  lib/archethic/p2p/message.ex
  lib/archethic/p2p/message/balance.ex
  lib/archethic/p2p/message/get_balance.ex
  lib/archethic/p2p/message/message_id.ex
  lib/archethic/reward.ex
  lib/archethic/utils/regression/benchmarks/p2p_message.ex
  lib/archethic/utxo.ex
  lib/archethic_web/api/graphql/schema/resolver.ex
  lib/archethic_web/explorer/live/chains/transaction_chain_live.ex
  lib/archethic_web/explorer/live/settings_live.ex
  test/archethic/bootstrap/network_init_test.exs
  test/archethic/bootstrap/sync_test.exs
  test/archethic/contracts/interpreter/library/common/chain_test.exs
  test/archethic/p2p/client/connection_test.exs
  test/archethic/p2p/messages_test.exs
  test/archethic/utxo_test.exs
  test/archethic_test.exs
  test/archethic_web/api/graphql/schema_test.exs
Labels: bug, P2P

#1471 Improve rebuild-utxo task
  lib/mix/tasks/db.ex
Labels: DB, enhancements

#1479 Optimize rebuild utxo command
  lib/mix/tasks/db.ex
Labels: DB, enhancements

#1481 Do not override first enrolled node on bootstrap
  lib/archethic/bootstrap/sync.ex
Labels: bug, bootstrap
