Repository archethic-foundation/archethic-node, pull requests merged in 2024-10, with the labels that each got.

#1559 Refactor replication validation
  lib/archethic/bootstrap/network_init.ex
  lib/archethic/contracts/interpreter/library/common/chain_impl.ex
  lib/archethic/mining/distributed_workflow.ex
  lib/archethic/mining/ledger_validation.ex
  lib/archethic/mining/pending_transaction_validation.ex
  lib/archethic/mining/standalone_workflow.ex
  lib/archethic/mining/validation_context.ex
  lib/archethic/p2p/message/validate_smart_contract_call.ex
  lib/archethic/replication.ex
  lib/archethic/replication/transaction_validator.ex
  lib/archethic/transaction_chain.ex
  lib/archethic/transaction_chain/transaction/cross_validation_stamp.ex
  lib/archethic/transaction_chain/transaction/validation_stamp/ledger_operations.ex
  lib/archethic/transaction_chain/transaction/validation_stamp/ledger_operations/transaction_movement.ex
  lib/archethic/utils/regression/playbooks/smart_contract/dex.ex
  lib/archethic_web/explorer/views/explorer_view.ex
  test/archethic/mining/distributed_workflow_test.exs
  test/archethic/mining/ledger_validation_test.exs
  test/archethic/mining/pending_transaction_validation_test.exs
  test/archethic/mining/validation_context_test.exs
  test/archethic/replication/transaction_validator_test.exs
  test/archethic/replication_test.exs
  test/archethic/transaction_chain/transaction/validation_stamp/ledger_operations_test.exs
  test/support/transaction_factory.ex
Labels: quality, enhancements

#1568 Use Elixir Version module on migrate version compare
  lib/mix/tasks/migrate.ex
Labels: bug, release

#1569 Replicate previous chain raise on missed tx
  lib/archethic/replication/transaction_context.ex
  test/archethic/replication/transaction_context_test.exs
Labels: bug, replication

#1573 Filter p2p view size on during aggregation of summaries
  lib/archethic/beacon_chain/summary_aggregate.ex
  test/archethic/beacon_chain/summary_aggregate_test.exs
Labels: bug, self repair

#1574 Consume inputs even if not genesis node
  lib/archethic/utxo.ex
  test/archethic/utxo_test.exs
Labels: bug, replication

#1575 Sort ownership authorized keys in serialization
  lib/archethic/transaction_chain/transaction/data/ownership.ex
Labels: serialization, enhancements

#1580 Fix aeweb case sensitivity for asset names
  lib/archethic_web/aeweb/controllers/web_hosting_controller.ex
  lib/archethic_web/aeweb/controllers/web_hosting_controller/resources.ex
  test/archethic_web/aeweb/controllers/web_hosting_controller_test.exs
Labels: bug, API, web hosting

#1582 Use the acceptance_resolver more often
  lib/archethic/mining/smart_contract_validation.ex
  lib/archethic/mining/transaction_context.ex
  lib/archethic/replication.ex
  lib/archethic/replication/transaction_context.ex
  lib/archethic/self_repair.ex
  lib/archethic/self_repair/sync.ex
  lib/archethic/transaction_chain.ex
  test/archethic/mining/distributed_workflow_test.exs
  test/archethic/mining/standalone_workflow_test.exs
  test/archethic/replication/transaction_context_test.exs
Labels: P2P

#1586 Add a repair function to the quorum read
  lib/archethic.ex
  lib/archethic/beacon_chain.ex
  lib/archethic/mining/pending_transaction_validation.ex
  lib/archethic/mining/smart_contract_validation.ex
  lib/archethic/networking/scheduler.ex
  lib/archethic/p2p.ex
  lib/archethic/p2p/message/get_bootstraping_nodes.ex
  lib/archethic/transaction_chain.ex
  lib/archethic_web/api/graphql/schema/resolver.ex
  priv/migration_tasks/prod/1.5.9@add_mining_bls_key.exs
  test/archethic/p2p_test.exs
  test/archethic/replication/transaction_context_test.exs
  test/support/template.ex
Labels: P2P
