Repository archethic-foundation/archethic-node, pull requests merged in 2024-11, with the labels that each got.

#1589 TaskSupervisor partitionning
  config/test.exs
  lib/archethic.ex
  lib/archethic/application.ex
  lib/archethic/beacon_chain.ex
  lib/archethic/beacon_chain/network_coordinates.ex
  lib/archethic/beacon_chain/slot/validation.ex
  lib/archethic/beacon_chain/subset.ex
  lib/archethic/beacon_chain/subset/p2p_sampling.ex
  lib/archethic/beacon_chain/update.ex
  lib/archethic/contracts.ex
  lib/archethic/contracts/interpreter/library/common/http_impl.ex
  lib/archethic/contracts/loader.ex
  lib/archethic/governance.ex
  lib/archethic/mining.ex
  lib/archethic/mining/distributed_workflow.ex
  lib/archethic/mining/pending_transaction_validation.ex
  lib/archethic/mining/smart_contract_validation.ex
  lib/archethic/mining/standalone_workflow.ex
  lib/archethic/mining/transaction_context.ex
  lib/archethic/networking/scheduler.ex
  lib/archethic/oracle_chain/services/hydrating_cache.ex
  lib/archethic/oracle_chain/services/uco_price/providers/coin_marketcap_archethic.ex
  lib/archethic/p2p.ex
  lib/archethic/p2p/listener_protocol.ex
  lib/archethic/p2p/message/add_mining_context.ex
  lib/archethic/p2p/message/replicate_pending_transaction_chain.ex
  lib/archethic/p2p/message/replicate_transaction.ex
  lib/archethic/replication.ex
  lib/archethic/self_repair/network_chain.ex
  lib/archethic/self_repair/notifier.ex
  lib/archethic/self_repair/scheduler.ex
  lib/archethic/self_repair/sync.ex
  lib/archethic/transaction_chain.ex
  lib/archethic/utils.ex
  lib/archethic_web/api/jsonrpc/controllers/jsonrpc_controller.ex
  lib/archethic_web/api/jsonrpc/methods/simulate_contract_execution.ex
  lib/archethic_web/api/rest/controllers/transaction_controller.ex
  lib/archethic_web/dashboard_metrics_aggregator.ex
  lib/archethic_web/explorer/live/transaction_details_live.ex
  lib/mix/tasks/db.ex
  lib/mix/tasks/migrate.ex
  priv/migration_tasks/prod/1.4.8@aeip_21-1.exs
  test/archethic/contracts/worker_test.exs
Labels: bug

#1593 Consume the MUCO correctly
  lib/archethic/bootstrap/network_init.ex
  lib/archethic/mining/ledger_validation.ex
  lib/archethic/mining/validation_context.ex
  lib/archethic/p2p/message/validate_smart_contract_call.ex
  test/archethic/mining/distributed_workflow_test.exs
  test/archethic/mining/ledger_validation_test.exs
  test/archethic/mining/validation_context_test.exs
  test/support/transaction_factory.ex
Labels: bug

#1591 Store proof of validation
  lib/archethic/db/embedded_impl/chain_reader.ex
  lib/archethic/db/embedded_impl/encoding.ex
  lib/archethic/mining.ex
  lib/archethic/mining/distributed_workflow.ex
  lib/archethic/mining/standalone_workflow.ex
  lib/archethic/mining/validation_context.ex
  lib/archethic/p2p/message/cross_validation_done.ex
  lib/archethic/p2p/message/replicate_pending_transaction_chain.ex
  lib/archethic/p2p/message/replicate_transaction.ex
  lib/archethic/p2p/message/validate_transaction.ex
  lib/archethic/replication.ex
  lib/archethic/replication/transaction_validator.ex
  lib/archethic/transaction_chain/transaction.ex
  lib/archethic/transaction_chain/transaction/cross_validation_stamp.ex
  lib/archethic/transaction_chain/transaction/proof_of_validation.ex
  lib/archethic_web/api/graphql/schema/transaction_type.ex
  lib/archethic_web/explorer/live/transaction_details_live.ex
  lib/archethic_web/explorer/live/transaction_details_live.html.heex
  test/archethic/db/embedded_impl_test.exs
  test/archethic/mining/distributed_workflow_test.exs
  test/archethic/mining/standalone_workflow_test.exs
  test/archethic/mining/validation_context_test.exs
  test/archethic/p2p/messages_test.exs
  test/archethic/replication/transaction_validator_test.exs
  test/archethic/replication_test.exs
  test/archethic/transaction_chain/transaction/cross_validation_stamp_test.exs
  test/archethic/transaction_chain/transaction/proof_of_validation_test.exs
  test/archethic/transaction_chain/transaction_test.exs
  test/support/contract_factory.ex
  test/support/template.ex
  test/support/transaction_factory.ex
Labels: mining, UI, DB, API

#1602 refactor quorum to run acceptance resolver once
  lib/archethic/p2p.ex
Labels: quality

#1590 Add timestamp in node validation election
  lib/archethic.ex
  lib/archethic/election.ex
  lib/archethic/mining.ex
  lib/archethic/mining/distributed_workflow.ex
  lib/archethic/mining/validation_context.ex
  lib/archethic/p2p/message/start_mining.ex
  test/archethic/election_test.exs
  test/archethic/mining/validation_context_test.exs
  test/support/transaction_factory.ex
Labels: feature, mining

#1588 Add the genesis address in the validation_stamp
  lib/archethic/bootstrap/network_init.ex
  lib/archethic/db/embedded_impl/chain_reader.ex
  lib/archethic/db/embedded_impl/chain_writer.ex
  lib/archethic/db/embedded_impl/encoding.ex
  lib/archethic/mining.ex
  lib/archethic/mining/distributed_workflow.ex
  lib/archethic/mining/validation_context.ex
  lib/archethic/transaction_chain/transaction/cross_validation_stamp.ex
  lib/archethic/transaction_chain/transaction/validation_stamp.ex
  lib/archethic_web/api/graphql/schema/transaction_type.ex
  lib/archethic_web/explorer/components/transactions_list.ex
  lib/archethic_web/explorer/live/chains/node_shared_secrets_chain_live.ex
  lib/archethic_web/explorer/live/chains/oracle_chain_live.ex
  lib/archethic_web/explorer/live/chains/origin_chain_live.ex
  lib/archethic_web/explorer/live/chains/reward_chain_live.ex
  lib/archethic_web/explorer/live/transaction_details_live.html.heex
  priv/migration_tasks/prod/1.6.0@genesis.exs
  test/archethic/db/embedded_impl_test.exs
  test/archethic/mining/distributed_workflow_test.exs
  test/archethic/mining/validation_context_test.exs
  test/archethic/p2p/messages_test.exs
  test/archethic/transaction_chain/transaction/cross_validation_stamp_test.exs
  test/archethic/transaction_chain/transaction/validation_stamp_test.exs
  test/archethic/transaction_chain/transaction_test.exs
  test/support/transaction_factory.ex
Labels: transaction

#1604 Update node version and dependencies version
  .tool-versions
  assets/package-lock.json
  assets/package.json
  priv/static/.keep
Labels: dependencies
