Repository archethic-foundation/archethic-node, pull requests merged in 2024-01, with the labels that each got.

#1362 Fix bug when there are 10 txs in last page
  lib/archethic/db/embedded_impl/chain_reader.ex
  test/archethic/db/embedded_impl_test.exs
Labels: bug

#1358 Add state unspent outputs in graphql
  lib/archethic_web/api/graphql/schema/transaction_type.ex
Labels: feature, smart contracts, API

#1366 Resolve distinct addresses
  lib/archethic/transaction_chain.ex
Labels: mining, enhancements

#1371 Explorer: TransactionDetails page bugfix
  lib/archethic_web/explorer/live/transaction_details_live.html.heex
Labels: bug

#1369 Fix issue in Notify workflow
  lib/archethic/mining/validation_context.ex
  test/archethic/mining/validation_context_test.exs
Labels: bug, mining, election

#1370 ListenerProtocol catch errors
  lib/archethic/p2p/listener_protocol.ex
Labels: bug, P2P

#1386 Scope assignation returns assigned value
  lib/archethic/contracts/interpreter/scope.ex
  test/archethic/contracts/interpreter/scope_test.exs
Labels: bug, smart contracts

#1384 Fix utxo token properties on explorer
  lib/archethic_web/explorer/live/transaction_details_live.ex
Labels: bug, UI

#1380 Fix regression on the explorer with invalid transactions
  lib/archethic_web/explorer/live/transaction_details_live.html.heex
Labels: bug, UI

#1378 Settings page rebrand
  assets/css/explorer.scss
  lib/archethic_web/explorer/live/settings_live.ex
  lib/archethic_web/explorer/live/settings_live.html.heex
  priv/static/cache_manifest.json
Labels: feature, UI

#1377 Add a button to open the node's explorer
  lib/archethic_web/explorer/live/node_details_live.html.heex
Labels: feature, UI

#1374 fix 🐛 (explorer): Use memory values for Oracle's explorer page
  lib/archethic_web/explorer/live/chains/oracle_chain_live.ex
  lib/archethic_web/explorer/live/chains/oracle_chain_live.html.heex
Labels: UI, enhancements

#1383 DashboardData uses a different struct
  lib/archethic/p2p/message/dashboard_data.ex
  test/archethic/p2p/message/dashboard_data_test.exs
  test/archethic_web/dashboard_metrics_test.exs
Labels: bug, P2P

#1376 Use the same timeout on all tasks related to network patches
  lib/archethic/beacon_chain/network_coordinates.ex
  lib/archethic/beacon_chain/subset.ex
  lib/archethic/beacon_chain/subset/stats_collector.ex
  lib/archethic/p2p/message/get_network_stats.ex
  test/archethic/beacon_chain/network_coordinates_test.exs
  test/archethic/beacon_chain/subset/stats_collector_test.exs
Labels: bug, beacon chain

#1389 Fix regression in TransactionChain.fetch
  lib/archethic/transaction_chain.ex
  test/archethic/transaction_chain_test.exs
Labels: bug

#1390 Fix regression introduced with rebranding explorer
  lib/archethic_web/explorer/components/transactions_list.ex
Labels: bug, UI

#1396 Compress the transaction code on serialization
  lib/archethic/bootstrap/network_init.ex
  lib/archethic/db/embedded_impl/encoding.ex
  lib/archethic/mining.ex
  lib/archethic/mining/pending_transaction_validation.ex
  lib/archethic/transaction_chain.ex
  lib/archethic/transaction_chain/transaction/data.ex
  lib/archethic/utils/regression/api.ex
  lib/archethic_web/api/ecto_schemas/schema/transaction_data.ex
  lib/archethic_web/api/jsonrpc/schemas/transaction.ex
  lib/archethic_web/explorer/live/transaction_details_live.html.heex
  priv/json-schemas/schemas/object/transaction_data.json
  test/archethic/contracts/contract_test.exs
  test/archethic/mining/pending_transaction_validation_test.exs
  test/archethic/transaction_chain/transaction_test.exs
  test/archethic_web/api/ecto_schemas/transaction_payload_test.exs
  test/archethic_web/api/jsonrpc/schemas/transaction_test.exs
  test/support/template.ex
Labels: feature, P2P, DB

#1397 Add new flag resolve_last to rpc call function
  lib/archethic_web/api/ecto_schemas/function_call_payload.ex
  lib/archethic_web/api/jsonrpc/methods/call_contract_function.ex
  test/archethic_web/api/jsonrpc/methods/call_contract_function_test.exs
Labels: feature, smart contracts, API
