Repository archethic-foundation/archethic-node, pull requests merged in 2024-02, with the labels that each got.

#1401 StatsCollector: fix flaky tests
  test/archethic/beacon_chain/subset/stats_collector_test.exs
Labels: bug, CI/CD

#1385 Integrate genesis address in self repair
  lib/archethic/beacon_chain/replication_attestation.ex
  lib/archethic/beacon_chain/slot.ex
  lib/archethic/beacon_chain/summary.ex
  lib/archethic/beacon_chain/summary_aggregate.ex
  lib/archethic/bootstrap/network_init.ex
  lib/archethic/election.ex
  lib/archethic/mining/distributed_workflow.ex
  lib/archethic/mining/standalone_workflow.ex
  lib/archethic/mining/validation_context.ex
  lib/archethic/p2p/message/replicate_pending_transaction_chain.ex
  lib/archethic/self_repair/notifier.ex
  lib/archethic/self_repair/sync.ex
  lib/archethic/self_repair/sync/transaction_handler.ex
  lib/archethic/transaction_chain.ex
  lib/archethic/transaction_chain/transaction_summary.ex
  lib/archethic/utxo/loader.ex
  lib/archethic/utxo/memory_ledger.ex
  test/archethic/beacon_chain/replication_attestation_test.exs
  test/archethic/beacon_chain/slot/validation_test.exs
  test/archethic/beacon_chain/slot_test.exs
  test/archethic/beacon_chain/subset/summary_cache_test.exs
  test/archethic/beacon_chain/subset_test.exs
  test/archethic/beacon_chain/summary_aggregate_test.exs
  test/archethic/beacon_chain/summary_test.exs
  test/archethic/db/embedded_impl_test.exs
  test/archethic/mining/distributed_workflow_test.exs
  test/archethic/mining/standalone_workflow_test.exs
  test/archethic/self_repair/sync/transaction_handler_test.exs
  test/archethic/self_repair/sync_test.exs
  test/archethic/transaction_chain/transaction_summary_test.exs
Labels: feature, self repair, AEIP

#1425 Prevent infinite loop on corrupted file
  lib/archethic/db/embedded_impl/chain_reader.ex
  test/archethic/db/embedded_impl_test.exs
Labels: bug, DB

#1430 Set a minimum concurrency so it is never 0
  lib/archethic/self_repair/notifier.ex
Labels: bug

#1428 Fix GetUnspentOutputs deserialization
  lib/archethic/p2p/message/get_unspent_outputs.ex
  test/archethic/p2p/message/get_unspent_outputs_test.exs
Labels: bug

#1437 Speedup node start by deactivating unused feature
  config/dev.exs
  config/prod.exs
  lib/archethic/contracts/loader.ex
Labels: enhancements

#1434 AEIP21-P2: Use genesis unspent outputs during transaction's validation
  lib/archethic.ex
  lib/archethic/mining/distributed_workflow.ex
  lib/archethic/mining/standalone_workflow.ex
  lib/archethic/mining/transaction_context.ex
  lib/archethic/mining/validation_context.ex
  lib/archethic/p2p/message/get_unspent_outputs.ex
  lib/archethic/replication.ex
  lib/archethic/replication/transaction_context.ex
  lib/archethic/replication/transaction_validator.ex
  lib/archethic/transaction_chain.ex
  lib/archethic/transaction_chain/transaction/cross_validation_stamp.ex
  lib/archethic/utxo/db_ledger/file_impl.ex
  lib/archethic_web/explorer/live/transaction_details_live.ex
  test/archethic/mining/transaction_context_test.exs
  test/archethic/mining/validation_context_test.exs
  test/archethic/replication/transaction_context_test.exs
  test/archethic/replication/transaction_validator_test.exs
  test/archethic/replication_test.exs
Labels: mining, AEIP

#1435 AEIP21-P2: UTXO synchronisation amongst validators
  lib/archethic/mining.ex
  lib/archethic/mining/distributed_workflow.ex
  lib/archethic/mining/validation_context.ex
  lib/archethic/p2p/client/connection.ex
  lib/archethic/p2p/listener_protocol.ex
  lib/archethic/p2p/message/add_mining_context.ex
  lib/archethic/p2p/message_envelop.ex
  lib/archethic/transaction_chain/transaction/validation_stamp/ledger_operations/versioned_unspent_output.ex
  test/archethic/mining/distributed_workflow_test.exs
  test/archethic/mining/validation_context_test.exs
  test/archethic/p2p/message/add_mining_context_test.exs
  test/archethic/p2p/messages_test.exs
  test/archethic/transaction_chain/transaction/validation_stamp/ledger_operations/versioned_unspent_output_test.exs
Labels: mining, AEIP

#1427 AEIP21-P2: Adapt graphql queries
  lib/archethic.ex
  lib/archethic/p2p/message/get_balance.ex
  lib/archethic/transaction_chain/transaction_input.ex
  lib/archethic/utxo.ex
  lib/archethic_web/api/graphql/schema/resolver.ex
  test/archethic_test.exs
  test/archethic_web/api/graphql/schema_test.exs
Labels: API, enhancements, AEIP
